### ISSUE TITLE
❤ it! How about a screenshot in your readme?  

### ISSUE THREAD

**Issue by PySimpleGUI** [aryanoutlaw/CODSOFT#1]
I really like what you did!  Very nice... I'm sure your visitors would like to see a screenshot.

If you paste one into a GitHub issue, like I did below, then you can get the line of markdown text that GitHub created, put it into your readme file and it'll embed the image.  No need to store the image in your repo or a file hosting service.

`![image](https://github.com/aryanoutlaw/CODSOFT/assets/46163555/3100b3a4-a137-41c7-8636-099723618a84)`

![image](https://github.com/aryanoutlaw/CODSOFT/assets/46163555/3100b3a4-a137-41c7-8636-099723618a84)

For the fun of it I played with it and added a couple of things you might be interested in (or not.... it's your code and your fun so take these are some ideas and nothing more):

* Converted the images into Base64 so that the project collapsed down into 1 single .py file
* Added a bind return key so when you enter the location, you can press return or click submit
* Moved your theme up higher so all elements were set using it
* Added Tabs so that the city selection and the weather are on different tabs.  This one is good if you are going to add more settings like a c/f select, etc.

Mine looks like this:

![image](https://github.com/aryanoutlaw/CODSOFT/assets/46163555/bfb472ba-84e7-4a07-bed8-782638902b5a)

You can see the code over on Trinket:

https://trinket.io/pygame/10c2d2ec4a

Very impressive work you've done!  I like everything about it.  ![image](https://github.com/aryanoutlaw/CODSOFT/assets/46163555/6324f799-45a2-4181-9977-9e1ccd0ef3c2)

**Comment by aryanoutlaw** [comment]
Worked up on your suggestions, Thanks.
